// CSS MODULES

import { GetStaticProps } from "next";
import Head from "next/head";
import Link from "next/link";
import { ProductType } from "types/types";

import styles from './product.module.scss';

const ProductList = ({products} : {products: ProductType[]}) => {
    const productList = products.map((item) => <li key={item.id}>  <Link href={`/products/${item.id}`}><a><h2> {item.title} {item.price}</h2></a></Link> </li>)
    return (
        <>
            <Head>
                <title> Next Tutorial | ProductList </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>ProductList</h1>
            <ul className={styles.products}>
                {productList}
            </ul>
        </>
    )
};


export const getStaticProps: GetStaticProps = async() => {

    const res = await fetch('http://localhost:4000/products');

    const products = await res.json();

    return {
        props: {
            products,
            noLayout: true,
        }
    }

}

export default ProductList;